%YAML:1.2
# SPDX-FileCopyrightText: 2021-2023 Smart Robotics Lab, Imperial College London, Technical University of Munich
# SPDX-License-Identifier: CC0-1.0

general:
  sensor_type:                "depth" # depth | ouster [not yet supported] | leica
  results_directory:          "/tmp"
  integration_type:           "ray"  # ray | rangeImage; option not yet supported, not used if sensor_type depth
  submap_time_threshold:      15.0
  submap_state_buffer:        1 # Buffer, if in 10 states we have not created a submap we start integrating it into supereight
  submap_kf_threshold:        10
  sensor_measurement_downsampling: 1
  depth_image_resolution_downsampling: 1

map:
  dim:            [25.6, 25.6, 25.6]
  res:            0.1
  free_space_res: 0.1

data:
  # occupancy data
  surface_boundary:        0
  min_occupancy:           -100
  max_occupancy:            100
  log_odd_min:             -5.015
  log_odd_max:              5.015
  fs_integr_scale:         1
  const_surface_thickness: false
  uncertainty_model:       quadratic
  tau_min_factor:          3
  tau_max_factor:          12
  k_tau:                   0.01
  sigma_min_factor:        1      # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  sigma_max_factor:        3      # minimum/maximum uncertainty := 3 x sigma_min_factor/sigma_max_factor * voxel_dim
  k_sigma:                 0.017

  # lidar ray integration
  k_scale: 6e-03

sensor:
  # Simulated Intel RealSense depth camera
  width:      640
  height:     480
  fx:         390.598938
  fy:         390.598938
  cx:         320.0
  cy:         240.0
<<<<<<< HEAD
  near_plane: 0.1
  far_plane:  8.0
=======
  near_plane: 0.6
  far_plane:  4.5
>>>>>>> 4336fc4... New configuration and meshes for the simulated forest
  scale:      1.0 # Scale factor to apply to the depth images received from the camera to convert them to meters
  T_BS:       [1.0, 0.0, 0.0, -0.0302200001,
               0.0, 1.0, 0.0,  0.0074000000,
               0.0, 0.0, 1.0,  0.0160200000,
               0.0, 0.0, 0.0,  1.0000000000]
